const menuData = {
    shawarma: [
        {
            id: 1,
            name: "Фирменная",
            description: "Классическая шаурма с нежным куриным филе",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 250, large: 340, xxl: 420 },
            kcals_per_100: 202,
            proteins_per_100: 10.2,
            fats_per_100: 9.5,
            carbs_per_100: 18.4,
            composition: "лаваш, курица, капуста, соус фирменный, томаты, огурцы",
            ingredients_to_remove: ["капуста", "соус фирменный", "томаты", "огурцы"],
            can_remove_chicken: true,
            has_sizes: true,
            in_stock: true,
            img: "images/clasic.jpg"
        },
        {
            id: 2,
            name: "Сырная",
            description: "Шаурма с сыром",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 260, large: 360, xxl: 450 },
            kcals_per_100: 218,
            proteins_per_100: 11.8,
            fats_per_100: 11.2,
            carbs_per_100: 17.9,
            composition: "лаваш, курица, капуста, соус фирменный, сыр, томаты, огурцы",
            ingredients_to_remove: ["капуста", "соус фирменный", "томаты", "огурцы"],
            can_remove_chicken: true,
            has_sizes: true,
            in_stock: true,
            img: "images/cheese.jpg"
        },
        {
            id: 3,
            name: "Дабл Чиз",
            description: "Двойная порция сыра",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 280, large: 380, xxl: 480 },
            kcals_per_100: 240,
            proteins_per_100: 13.5,
            fats_per_100: 13.8,
            carbs_per_100: 17.2,
            composition: "лаваш, курица, капуста, соус фирменный, соус сырный, сыр, томаты, огурцы",
            ingredients_to_remove: ["капуста", "соус фирменный", "томаты", "огурцы"],
            can_remove_chicken: true,
            has_sizes: true,
            in_stock: true,
            img: "images/cheese.jpg"
        },
        {
            id: 4,
            name: "Гавайская",
            description: "Шаурма с ананасами",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 270, large: 370, xxl: 460 },
            kcals_per_100: 205,
            proteins_per_100: 9.8,
            fats_per_100: 9.2,
            carbs_per_100: 20.1,
            composition: "лаваш, курица, пекинская капуста, соус фирменный, сыр, томаты, ананасы консервированные",
            ingredients_to_remove: ["пекинская капуста", "соус фирменный", "сыр", "томаты"],
            can_remove_chicken: true,
            has_sizes: true,
            in_stock: true,
            img: "images/gawaii.jpg"
        },
        {
            id: 5,
            name: "Мясная",
            description: "Удвоенная порция мяса",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 270, large: 370, xxl: 460 },
            kcals_per_100: 210,
            proteins_per_100: 12.0,
            fats_per_100: 9.8,
            carbs_per_100: 18.0,
            composition: "лаваш, курица, капуста, соус фирменный, томаты, огурцы",
            ingredients_to_remove: ["капуста", "соус фирменный", "томаты", "огурцы"],
            can_remove_chicken: false,
            has_sizes: true,
            in_stock: true,
            img: "images/nope.jpg"
        },
        {
            id: 6,
            name: "Грибная",
            description: "Шаурма с грибами",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 260, large: 360, xxl: 450 },
            kcals_per_100: 208,
            proteins_per_100: 10.5,
            fats_per_100: 10.0,
            carbs_per_100: 18.5,
            composition: "лаваш, курица, пекинская капуста, соус фирменный, соус грибной, шампиньоны, томаты, огурцы",
            ingredients_to_remove: ["пекинская капуста", "соус фирменный", "соус грибной", "томаты", "огурцы"],
            can_remove_chicken: true,
            has_sizes: true,
            in_stock: false,
            img: "images/nope.jpg"
        },
        {
            id: 7,
            name: "Барбекю",
            description: "Шаурма с беконом и соусом барбекю",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 270, large: 360, xxl: 460 },
            kcals_per_100: 228,
            proteins_per_100: 11.8,
            fats_per_100: 12.5,
            carbs_per_100: 18.2,
            composition: "лаваш, курица, капуста, соус фирменный, соус барбекю, бекон, томаты, огурцы",
            ingredients_to_remove: ["капуста", "соус фирменный", "соус барбекю", "томаты", "огурцы"],
            can_remove_chicken: true,
            has_sizes: true,
            in_stock: false,
            img: "images/nope.jpg"
        },
        {
            id: 8,
            name: "С креветками",
            description: "Шаурма с креветками",
            weight: { medium: 300, large: 450, xxl: 550 },
            price: { medium: 300, large: 410, xxl: 510 },
            kcals_per_100: 204,
            proteins_per_100: 12.4,
            fats_per_100: 9.0,
            carbs_per_100: 17.5,
            composition: "лаваш, пекинская капуста, соус фирменный, сыр, креветки, томаты, лимонный сок",
            ingredients_to_remove: ["пекинская капуста", "соус фирменный", "сыр", "томаты", "лимонный сок"],
            can_remove_chicken: true,
            has_sizes: true,
            in_stock: false,
            img: "images/nope.jpg"
        },
        {
            id: 9,
            name: "Мини-шаурма",
            description: "Компактная шаурма 220г",
            weight: 220,
            price: 200,
            kcals_per_100: 202,
            proteins_per_100: 10.2,
            fats_per_100: 9.5,
            carbs_per_100: 18.4,
            composition: "лаваш, курица, капуста, соус фирменный, томаты, огурцы",
            ingredients_to_remove: ["капуста", "соус фирменный", "томаты", "огурцы"],
            can_remove_chicken: true,
            has_sizes: false,
            in_stock: true,
            img: "images/clasic.jpg"
        }
    ],
    salads: [
        // В разработке
    ],
    snacks: [
        // В разработке
    ],
    drinks: [
        {
            id: 30,
            name: "Сок апельсиновый",
            description: "J7 Апельсин с мякотью, без сахара, 0.97L",
            weight: 970,
            price: 250,
            kcals: 39,
            proteins: 0.7,
            fats: 0,
            carbs: 9,
            composition: "апельсиновый сок 100%",
            has_sizes: false,
            in_stock: true,
            is_drink: true,
            img: "images/orange.jpg"
        },
        {
            id: 31,
            name: "Сок яблочный",
            description: "ДОБРЫЙ Яблоко, без сахара, 1L",
            weight: 1000,
            price: 250,
            kcals: 42,
            proteins: 0,
            fats: 0,
            carbs: 10.5,
            composition: "яблочный сок 100%",
            has_sizes: false,
            in_stock: true,
            is_drink: true,
            img: "images/apple.jpg"
        }
    ]
};